### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by websters-dog**
I expierenced some troubles with nested navigators, so I added ability to pass overlay parameter.
Also I required dismissing tooltip on scroll. For this purpose I added SuperTooltipDismissBehaviour with onPointerDown Listener with translucent hit test.

### CODE REVIEW

**Comment by escamoteur** [comment]
I'm sorry but you seem to have reformated the whole file so that I can't see where you made which changes

**Comment by escamoteur** [comment]
Please change the PR so hat I can see the changes.

**Comment by websters-dog** [comment]
Sorry, I missed formatting setup in my IDE. I'll fix it

**Comment by websters-dog** [comment]
Done!

**Comment by escamoteur** [comment]
why would you handle tap differently from pointer down?

**Comment by websters-dog** [comment]
It's useful in situation, when tooltip with transparent backgournd placed in scroll. Tooltip can be silently hidden on pointer down event and scroll widget gets event and works as it's required.

**Comment by escamoteur** [comment]
but does pointer down also get called if you tap on a touchscreen? 
you mean you problem is you don't want to swallow the drag events?

**Comment by escamoteur** [comment]
but why would we then keep the onTap at all?

**Comment by websters-dog** [comment]
In some situations it can be useful. For example when background has color. I guess current users also can rely on such behaviour.

**Comment by escamoteur** [comment]
ah, right the onTap respects the backgound color and also the cutout of the background. I guess that's not possible with the listeners. isn't it possible to make a GestureDetector not swallow the event?

**Comment by escamoteur** [comment]
I wonder if it makes sense ever to block the other events

**Comment by escamoteur** [comment]
yeah then lets go that way. adding a bool parameter that blocks as default all then it's not a breaking change at all what do you think?

**Comment by websters-dog** [comment]
I think it's ok. I'll use `Listener` with `onPointerDown` to hide tooltip before any scroll can happen for any blocking parameter value. Or will it be better to use on 'GestureDetector` + `onTap` when value is `true` and `Listener` + `onPointerDown` on `false`?

**Comment by escamoteur** [comment]
how does a listener behave if you have a cut-out in the background? when you tap this area we should not react

**Comment by websters-dog** [comment]
Sorry, I missed cut-out, need to check it

**Comment by websters-dog** [comment]
I reworked PR to bool property `blockOutsidePointerEvents`. It's true by default. If `blockOutsidePointerEvents` set to false events go through background and if `dismissOnTapOutside` is also true tooltip disapprears `onPointerDown`, but when you tap on cut-out tooltip stays on screen.

**Comment by escamoteur** [comment]
looks got to me. I'm in the process of handing over maintenance of this package to some friends, so I want them also to have a look at this. I you are interested to also become a maintainer let me know. I will move the package soon over to the Flutter Community organisation.

**Review by mrverdant13 — APPROVED** [review]
Looks great to me

**Comment by escamoteur** [comment]
ok, I have merged it now but this changes have to be reviews and ported to the V2 branch too

**Pull request merged**
