### PR TITLE
Allow to change the close Icon

### PR DESCRIPTION
**Pull request by tbarbette**

### CODE REVIEW

**Comment by escamoteur** [comment]
could you update the changelog please?

**Comment by tbarbette** [comment]
Like this?

**Comment by escamoteur** [comment]
Yep, perfect. I will probably push the new version tomorrow
Am 15. März 2021, 18:21 +0100 schrieb Tom Barbette ***@***.***>:

**Comment by escamoteur** [comment]
pushed a new version

**Pull request merged**
